@extends('template/principal')
@section('contenido')
<div class="p-y-2">
        <div class="mis-terminos container">
            <h2>TÉRMINOS Y CONDICIONES</h2>
            <p>Este documento describe los términos y condiciones generales (los "Términos y Condiciones Generales") y las políticas de privacidad (las "Políticas de Privacidad") aplicables al acceso y uso de los servicios ofrecidos por SecondTime PERÚ S.A.C. ("los Servicios") dentro del sitio www.SecondTime.com.pe, sus subdominios y/u otros dominios (urls) relacionados (en adelante "SecondTime.com" o el "Sitio"), en donde éstos Términos y Condiciones se encuentren. Cualquier persona que desee acceder y/o suscribirse y/o usar el Sitio o los Servicios podrá hacerlo sujetándose a los Términos y Condiciones Generales y las Políticas de Privacidad, junto con todas las demás políticas y principios que rigen SecondTime.com.pe y que son incorporados al presente directamente o por referencia o que son explicados y/o detallados en otras secciones del Sitio. En consecuencia, todas las visitas y todos los contratos y transacciones que se realicen en este Sitio, así como sus efectos jurídicos, quedarán regidos por estas reglas y sometidos a la legislación aplicable en Perú.</p>
            <p>Los Términos y Condiciones y las Políticas de Privacidad contenidos en este instrumento se aplicarán y se entenderán como parte integral de todos los actos y contratos que se ejecuten o celebren mediante los sistemas de oferta y comercialización comprendidos en este sitio entre los usuarios de este sitio y SecondTime PERÚ S.A.C. (en adelante "SecondTime PERÚ S.A.C.", "SecondTime" o "la Empresa", indistintamente), y por cualquiera de las otras sociedades o empresas que sean filiales o vinculadas a ella, y que hagan uso de este sitio, a las cuales se las denominará en adelante también en forma indistinta como las "Empresas", o bien la "Empresa Oferente", el "Proveedor" o la "Empresa Proveedora", según convenga al sentido del texto.</p>
            <p>En caso que las Empresas hubieran fijado sus propios Términos y Condiciones y sus Políticas de Privacidad para los actos y contratos que realicen en este sitio, ellas aparecerán en esta página señalada con un link o indicada como parte de la promoción de sus ofertas y promociones y prevalecerán sobre éstas. CUALQUIER PERSONA QUE NO ACEPTE ESTOS TÉRMINOS Y CONDICIONES GENERALES Y LAS POLÍTICAS DE PRIVACIDAD, LOS CUALES TIENEN UN CARÁCTER OBLIGATORIO Y VINCULANTE, DEBERÁ ABSTENERSE DE UTILIZAR EL SITIO Y/O LOS SERVICIOS.</p>
            <p>El Usuario debe leer, entender y aceptar todas las condiciones establecidas en los Términos y Condiciones Generales y en las Políticas de Privacidad de SecondTime PERÚ S.A.C. así como en los demás documentos incorporados a los mismos por referencia, previo a su registro como Usuario de SecondTime.com.pe y/o a la adquisición de productos y/o entrega de cualquier dato, quedando sujetos a lo señalado y dispuesto en los Términos y Condiciones. </p>
            <p>Cuando usted visita SecondTime.com.pe se está comunicando con SecondTime de manera electrónica. En ese sentido, usted brinda su consentimiento para recibir comunicaciones de SecondTime por correo electrónico o mediante la publicación de avisos en su portal.</p>

            <h3>1. Capacidad Legal</h3>
            <p>Los Servicios sólo están disponibles para personas que tengan capacidad legal para contratar. No podrán utilizar los servicios las personas que no tengan esa capacidad entre estos los menores de edad o Usuarios de SecondTime.com.pe que hayan sido suspendidos temporalmente o inhabilitados definitivamente en razón de lo dispuesto en la sección 2 “Registro y Uso del Sitio”. Los actos que  los menores realicen en este sitio serán responsabilidad de sus padres, tutores, encargados o curadores, y por tanto se considerarán realizados por éstos en ejercicio de la representación legal con la que cuentan.</p>
            <p>Quien registre un Usuario como empresa afirmará que (i) cuenta con capacidad para contratar en representación de tal entidad y de obligar a la misma en los términos de este Acuerdo, (ii) la dirección señalada en el registro es el domicilio principal Legal y/o Fiscal de dicha entidad, y (iii) cualquier otra información presentada a SecondTime es verdadera, precisa, actualizada, completa y oportuna.</p>
            <h3>2. Registro y Uso del Sitio</h3>
            <p>Es obligatorio completar el formulario de registro en todos sus campos con datos válidos y verdaderos para convertirse en Usuario autorizado de SecondTime.com.pe (el "Miembro" SecondTime o el "Usuario"), de esta manera, podrá acceder a las promociones, y a la adquisición de productos y/o servicios ofrecidos en este sitio. El futuro Miembro SecondTime deberá completar el formulario de registro con su información personal de manera exacta, precisa y verdadera ("Datos Personales") y asume el compromiso de actualizar los Datos Personales conforme resulte necesario. SecondTime podrá utilizar diversos medios para identificar a sus Miembros, pero SecondTime NO se responsabiliza por la certeza de los Datos Personales provistos por sus Usuarios. Los Usuarios garantizan y responden, en cualquier caso, de la exactitud, veracidad, vigencia y autenticidad de los Datos Personales ingresados. En ese sentido, la declaración realizada por los Usuarios al momento de registrarse se entenderá como una Declaración Jurada.</p>
            <p>Cada miembro sólo podrá ser titular de una (1) cuenta SecondTime, no pudiendo acceder a más de una (1) cuenta SecondTime con distintas direcciones de correo electrónico o falseando, modificando y/o alterando sus datos personales de cualquier manera posible. En caso se detecte esta infracción, SecondTime se comunicará con el cliente informándole que todas sus cuentas serán agrupadas en una sola cuenta anulándose todas sus demás cuentas, ello se informara al usuario mediante correo electrónico indicado por él mismo o el último registrado en SecondTime.</p>
            <p>Si se verifica o sospecha algún uso fraudulento y/o malintencionado y/o contrario a estos Términos y Condiciones y/o contrarios a la buena fe, SecondTime tendrá el derecho inapelable de dar por terminados los créditos, no hacer efectiva las promociones, cancelar las transacciones en curso, dar de baja las cuentas y hasta de perseguir judicialmente a los infractores</p>
            <p>SecondTime podrá realizar los controles que crea convenientes para verificar la veracidad de la información dada por el Usuario. En ese sentido, se reserva el derecho de solicitar algún comprobante y/o dato adicional a efectos de corroborar los Datos Personales, así como de suspender temporal o definitivamente a aquellos Usuarios cuyos datos no hayan podido ser confirmados. En caso de suspensión temporal SecondTime comunicara al cliente informando el tiempo de suspensión de la cuenta. En casos de inhabilitación, SecondTime podrá dar de baja la compra efectuada, sin que ello genere derecho alguno a resarcimiento, pago y/o indemnización.</p>

            <h3>3. Procedimiento para Hacer Uso de Este Sitio de Internet</h3>
            <p>En los contratos ofrecidos por medio del Sitio, SecondTime.com.pe informará, de manera inequívoca y fácilmente accesible, los pasos que deberán seguirse para celebrarlos, e informará, cuando corresponda, si el documento electrónico en que se formalice el contrato será archivado y si éste será accesible al Usuario. El sólo hecho de seguir los pasos que para tales efectos se indiquen en este sitio para efectuar una compra, equivale a aceptar que efectivamente ha dado cumplimiento a las condiciones contenidas en este apartado. Indicará, además, su dirección de correo postal o electrónico y los medios técnicos a disposición del Miembro para identificar y corregir errores en el envío o en sus datos.</p>

            <h3>4. Medios de Pago que se Podrán Utilizar en el Sitio</h3>
            <p>Los productos y servicios ofrecidos en el Sitio, salvo que se señale una forma diferente para casos particulares u ofertas de determinados bienes o servicios, sólo pueden ser pagados con los medios que en cada caso específicamente se indiquen. El uso de tarjetas de créditos o débito se sujetará a lo establecido en estos Términos y Condiciones y, en relación con su emisor, y a lo pactado en los respectivos Contratos de Apertura y Reglamento de Uso. En caso de contradicción, predominará lo expresado en ese último instrumento. Tratándose de tarjetas bancarias aceptadas en el Sitio, los aspectos relativos a éstas, tales como la fecha de emisión, caducidad, cupo, bloqueos, cobros de comisiones, interés de compra en cuotas etc., se regirán por el respectivo Contrato de Apertura y Reglamento de Uso, de tal forma que las Empresas no tendrán responsabilidad por cualquiera de los aspectos señalados. El Sitio podrá indicar determinadas condiciones de compra según el medio de pago que se utilice por el usuario. SecondTime podrá otorgar descuento en la forma de créditos que los Usuarios podrán descontar en su compra. En cada caso SecondTime determinará unilateralmente el monto máximo de créditos que el Usuario podrá utilizar en una compra y lo detallará en el sistema, previo a iniciar el proceso de pago. Los créditos utilizados por los Usuarios serán reintegrados en aquellos casos en los que proceda conforme a la Política de Devoluciones y Garantías, y de acuerdo con la regulación.</p>

            <h3>5. Plazo de Validez de la Oferta y Precio</h3>
            <p>El plazo de validez de la oferta es aquel que coincide con la fecha de vigencia indicada en la promoción o en virtud del agotamiento de las cantidades de productos disponibles para esa promoción debidamente informados al Usuario, o mientras la oferta se mantenga disponible, el menor de éstos plazos. Cuando quiera que en una promoción no se indique una fecha de terminación se entenderá que la actividad se extenderá hasta el agotamiento de los inventarios correspondientes.</p>
            <p>Los precios de los productos y servicios disponibles en el Sitio, mientras aparezcan como disponibles, solo tendrán vigencia y aplicación en éste y no serán aplicables a otros canales de venta utilizados por las empresas, tales como, venta telefónica, otros sitios de venta por vía electrónica, catálogos u otros. Los precios de los productos ofrecidos en el Sitio están expresados en Soles o su conversión en moneda extranjera si fuera el caso. Los precios ofrecidos corresponden exclusivamente al valor del bien ofrecido y no incluyen gastos de transporte, manejo, envío, accesorios que no se describan expresamente ni ningún otro ítem adicional o cobro de intereses bancarios por el método de pago utilizado.</p>

            <h3>6. Motivos de Devolución</h3>
            <ul>
                <li type="circle">Producto defectuoso/no funciona bien</li>
                <li type="circle">Producto diferente a la descripción en la página web</li>
                <li type="circle">Producto disponible a mejor precio</li>
                <li type="circle">El producto no cumple con las expectativas</li>
                <li type="circle">Faltan partes o accesorios de este producto</li>
                <li type="circle">No es el producto comprado</li>
                <li type="circle">Pedido accidental</li>
            </ul>
        </div>
    </div>
@endsection